### ISSUE TITLE
Instalacion en laravel 5.2

### ISSUE THREAD

**Issue by andradedev** [dinkbit/conekta-cashier#12]
Hola, estoy tratando de usar el paquete en laravel 5.2, y al momento de instalarlo me retorna varios errores de requerimiento de paquetes, cuando liberaran la version para laravel 5.2?

**Comment by joecohens** [comment]
Hola! Lo actualizaremos lo antes posible. Voy a dejar este issue abierto hasta que lo actualicemos.

**Comment by joecohens** [comment]
Listo puedes usar la version v2.1.4 para poder usarlo con Laravel 5.2, cualquier cosa nos avisas.

Gracias!
