### ISSUE TITLE
Conekta webhook

### ISSUE THREAD

**Issue by juanmendez92** [dinkbit/conekta-cashier#15]
El único webhook que me funciona es el de la ruta que pones de ejemplo con la función handleWebhook. Al hacer uno nuevo, si este recibe algún parámetro empieza a fallar. Ya probé quitando tanto la palabra array  como dejándola y nada.

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Dinkbit\ConektaCashier\WebhookController as WebhookController;

class WebhookController extends WebhookController
{
    public function failed(array $payload) {

    }
}
```

**Comment by juanmendez92** [comment]
Lo solucioné, quité el parámetro $payload y en su lugar usé la función getJsonPayload() para obtener el JSON que envía conecta y tratar los eventos correctamente.

**Comment by joecohens** [comment]
👍 cualquier cosa estamos pendientes!
