### ISSUE TITLE
Obtener siguiente fecha de pago y monto de la subscripción

### ISSUE THREAD

**Issue by rcevs** [dinkbit/conekta-cashier#24]
¿Cuál sería la manera más sencilla o ideal de obtener la fecha en la que será el siguiente cobro y el monto de la suscripción? 

Veo que existe un parámetro llamdo "billing_cycle_end" que podría utilizar pero no encuentro una manera fácil o nativa de obtenerlo a través de Cashier.

Gracias

**Comment by juanmendez92** [comment]
A través de un webhook, con el evento subscription.paid obtienes el objeto que viene justamente con el parámetro que buscas.

**Comment by rcevs** [comment]
Muchas gracias Juan. Saludos.
