### ISSUE TITLE
No se puede instalar con Laravel 5.4 y actualizar Conekta a 3.0

### ISSUE THREAD

**Issue by juanmendez92** [dinkbit/conekta-cashier#27]
Hola, acabo de empezar con la versión 5.4 de Laravel pero me da problemas a la hora de instalar el paquete, esto es lo que sale

vagrant@homestead:~/Code/vistas$ clear
vagrant@homestead:~/Code/vistas$ composer require dinkbit/conekta-cashier
Using version ^2.2 for dinkbit/conekta-cashier
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install dinkbit/conekta-cashier v2.2.1
    - Conclusion: remove laravel/framework v5.4.4
    - Installation request for dinkbit/conekta-cashier ^2.2 -> satisfiable by dinkbit/conekta-cashier[v2.2.0, v2.2.1].
    - Conclusion: don't install laravel/framework v5.4.4
    - dinkbit/conekta-cashier v2.2.0 requires illuminate/support 5.0.*|5.1.*|5.2.*|5.3.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.4.4
    - Installation request for laravel/framework (locked at v5.4.4, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.4].

Installation failed, reverting ./composer.json to its original content.

Además de que ya requiere la actualización a la nueva versión de Conekta.

**Comment by joecohens** [comment]
Done https://github.com/dinkbit/conekta-cashier/pull/30
