### ISSUE TITLE
PHP Error Call to undefined method:  $user->subscription()->canceled() 

### ISSUE THREAD

**Issue by alfonsofernandezyf** [dinkbit/conekta-cashier#37]
I get a call to undefined method error when using the $user->subscription()->canceled() method.

PHP Error:  Call to undefined method Dinkbit\ConektaCashier\ConektaGateway::canceled() on line 1

**Comment by sgtpepper9907** [comment]
I believe de method name is `cancel`  
If you want to check if the user is subscribed (the account is not cancelled) you should use the method `subscribed`

```php
  $user->subscription()->cancel();
  $user->subscribed(); // false
```

**Comment by alfonsofernandezyf** [comment]
I wanted to tell if a custumer had been subscribed and then cancelled.
The method `$user->cancelled()` works fine.

Thank you.
